package com.genrocket.bank.testData

import com.genRocket.tdl.LoaderDTO
import com.genrocket.bank.CardType
import com.genrocket.bank.testDataLoader.CardTypeTestDataLoader
import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class CardTypeTestDataService {
  static transactional = true

  def cardTypeService

  def loadData(Integer loopCount = 1, Map<String, Object> domainMap = null) {
    println "Loading data for CardType..."

    if (CardType.count() == 0) {

      def cardTypeList = (LoaderDTO[]) CardTypeTestDataLoader.load(loopCount)

      cardTypeList.each { node ->
        def cardType = (CardType) node.object

        cardTypeService.save(cardType)
      }
    }
  }
}
    