package com.genrocket.bank.testData

import com.genRocket.tdl.LoaderDTO
import org.springframework.transaction.annotation.Transactional

import com.genrocket.bank.testDataLoader.CardPoolTestDataLoader
import com.genrocket.bank.CardPool

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class CardPoolTestDataService {
  static transactional = true

  def cardPoolService

  def loadData(Integer loopCount = 1, Map<String, Object> domainMap = null) {
    println "Loading data for CardPool..."

    if (CardPool.count() == 0) {

      def cardPoolList = (LoaderDTO[]) CardPoolTestDataLoader.load(loopCount)

      cardPoolList.each { node ->
        def cardPool = (CardPool) node.object

        cardPoolService.save(cardPool)
      }
    }
  }
}
    