package com.genrocket.bank.testData

import com.genRocket.tdl.LoaderDTO
import org.springframework.transaction.annotation.Transactional

import com.genrocket.bank.testDataLoader.CustomerLevelTestDataLoader
import com.genrocket.bank.CustomerLevel

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class CustomerLevelTestDataService {
  static transactional = true

  def customerLevelService

  def loadData(Integer loopCount = 1, Map<String, Object> domainMap = null) {
    println "Loading data for CustomerLevel..."

    if (domainMap) {
    }


    if (CustomerLevel.count() == 0) {

      def customerLevelList = (LoaderDTO[]) CustomerLevelTestDataLoader.load(loopCount)

      customerLevelList.each { node ->
        def customerLevel = (CustomerLevel) node.object

        customerLevelService.save(customerLevel)
      }
    }
  }
}
    