package com.genrocket.bank

import com.genRocket.tdl.LoaderDTO
import com.genrocket.bank.testDataLoader.AccountTypeTestDataLoader
import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class AccountTypeServiceIntegrationSpec extends IntegrationSpec {
  def accountTypeTestDataService
  def accountTypeService

  void "create accountType"() {
    given:


    when:

    def accountTypeList = (List<LoaderDTO>) AccountTypeTestDataLoader.load()
    def accountType = (AccountType) accountTypeList.first().object

    accountTypeService.save(accountType)

    then:

    accountType.id
  }

  void "update accountType"() {
    given:

    accountTypeTestDataService.loadData()
    def accountType = AccountType.first()
    def id = accountType.id

    when:

    accountType.name = 'TEST'
    accountTypeService.update(accountType)

    then:

    def temp = AccountType.get(id)
    temp.name == 'TEST'
  }

  void "delete accountType"() {
    given:

    accountTypeTestDataService.loadData()
    def accountType = AccountType.first()
    def id = accountType.id

    when:

    accountTypeService.delete(accountType)

    then:

    AccountType.get(id) == null
  }

}
    