package com.genrocket.bank

import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class AccountServiceIntegrationSpec extends IntegrationSpec {
  def accountTestDataService
  def accountService

  void "update account"() {
    given:

    accountTestDataService.loadData()
    def account = Account.first()
    def id = account.id

    when:

    Integer balance = account.balance + 1000
    account.balance = balance
    accountService.update(account)

    then:

    def temp = Account.get(id)
    temp.balance == balance
  }

  void "delete account"() {
    given:

    accountTestDataService.loadData()
    def account = Account.first()
    def id = account.id

    when:

    accountService.delete(account)

    then:

    Account.get(id) == null
  }


  void "test accountType for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.accountType = null

    when:

    accountService.update(account);

    then:

    account.errors.getFieldError("accountType").code == "nullable"

  }

  void "test balance for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.balance = null

    when:

    accountService.update(account);

    then:

    account.errors.getFieldError("balance").code == "nullable"

  }

  void "test branch for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.branch = null

    when:

    accountService.update(account);

    then:

    account.errors.getFieldError("branch").code == "nullable"

  }
}
    