package com.genrocket.bank

import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class AccountServiceConstraintSpec extends IntegrationSpec {
  def accountTestDataService

  void "test accountType for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.accountType = null

    when:

    account.save();

    then:

    account.errors.getFieldError("accountType").code == "nullable"

  }

  void "test balance for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.balance = null

    when:

    account.save();

    then:

    account.errors.getFieldError("balance").code == "nullable"
  }

  void "test branch for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.branch = null

    when:

    account.save();

    then:

    account.errors.getFieldError("branch").code == "nullable"
  }

  void "test accountNumber for Null"() {
    given:

    accountTestDataService.loadData()
    Account account = Account.first()
    account.accountNumber = null

    when:

    account.save();

    then:

    account.errors.getFieldError("accountNumber").code == "nullable"

  }

}
    