package com.genrocket.bank

import com.genRocket.tdl.LoaderDTO
import com.genrocket.bank.testDataLoader.BranchTestDataLoader
import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class BranchServiceIntegrationSpec extends IntegrationSpec {
  def branchTestDataService
  def branchService

  void "create branch"() {
    given:


    when:

    def branchList = (List<LoaderDTO>) BranchTestDataLoader.load()
    def branch = (Branch) branchList.first().object

    branchService.save(branch)

    then:

    branch.id
  }

  void "update branch"() {
    given:

    branchTestDataService.loadData()
    def branch = Branch.first()
    def id = branch.id

    when:

    branch.name = 'TEST'
    branchService.update(branch)

    then:

    def temp = Branch.get(id)
    temp.name == 'TEST'
  }

  void "delete branch"() {
    given:

    branchTestDataService.loadData()
    def branch = Branch.first()
    def id = branch.id

    when:

    branchService.delete(branch)

    then:

    Branch.get(id) == null
  }
}
    