package com.genrocket.bank

import com.genRocket.tdl.LoaderDTO
import com.genrocket.bank.testDataLoader.CustomerLevelTestDataLoader
import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class CustomerLevelServiceIntegrationSpec extends IntegrationSpec {
  def customerLevelTestDataService
  def customerLevelService

  void "create customerLevel"() {
    given:


    when:

    def customerLevelList = (List<LoaderDTO>) CustomerLevelTestDataLoader.load()
    def customerLevel = (CustomerLevel) customerLevelList.first().object

    customerLevelService.save(customerLevel)

    then:

    customerLevel.id
  }

  void "update customerLevel"() {
    given:

    customerLevelTestDataService.loadData()
    def customerLevel = CustomerLevel.first()
    def id = customerLevel.id

    when:

    customerLevel.name = 'TEST'
    customerLevelService.update(customerLevel)

    then:

    def temp = CustomerLevel.get(id)
    temp.name == 'TEST'
  }

  void "delete customerLevel"() {
    given:

    customerLevelTestDataService.loadData()
    def customerLevel = CustomerLevel.first()
    def id = customerLevel.id

    when:

    customerLevelService.delete(customerLevel)

    then:

    CustomerLevel.get(id) == null
  }
}
    