package com.genrocket.bank

import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class CustomerServiceConstraintSpec extends IntegrationSpec {
  def customerTestDataService
  def customerService

  void "test account for Null"() {
    given:

    customerTestDataService.loadData()
    Customer customer = Customer.first()
    customer.account = null

    when:

    customer.save()

    then:

    customer.errors.getFieldError("account").code == "nullable"

  }

  void "test customerLevel for Null"() {
    given:

    customerTestDataService.loadData()
    Customer customer = Customer.first()
    customer.customerLevel = null

    when:

    customer.save()

    then:

    customer.errors.getFieldError("customerLevel").code == "nullable"

  }

  void "test enabled for Null"() {
    given:

    customerTestDataService.loadData()
    Customer customer = Customer.first()
    customer.enabled = null

    when:

    customer.save()

    then:

    customer.errors.getFieldError("enabled").code == "nullable"

  }

  void "test user for Null"() {
    given:

    customerTestDataService.loadData()
    Customer customer = Customer.first()
    customer.user = null

    when:

    customer.save()

    then:

    customer.errors.getFieldError("user").code == "nullable"

  }

  void "test enable true"() {
    given:

    customerTestDataService.loadData()
    Customer customer = Customer.first()
    Integer id = customer.id

    customer.enabled = false
    customer.save()

    when:

    customerService.enableCustomer(customer)
    customer = Customer.get(id)

    then:

    customer.enabled
  }

  void "test enable false"() {
    given:

    customerTestDataService.loadData()
    Customer customer = Customer.first()
    Integer id = customer.id

    customer.enabled = true
    customer.save()

    when:

    customerService.disableCustomer(customer)
    customer = Customer.get(id)

    then:

    !customer.enabled
  }
}
    