package com.genrocket.bank

import com.genRocket.tdl.LoaderDTO
import com.genrocket.bank.testDataLoader.TransactionTypeTestDataLoader
import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class TransactionTypeServiceIntegrationSpec extends IntegrationSpec {
  def transactionTypeTestDataService
  def transactionTypeService

  void "create transactionType"() {
    given:


    when:

    def transactionTypeList = (List<LoaderDTO>) TransactionTypeTestDataLoader.load()
    def transactionType = (TransactionType) transactionTypeList.first().object

    transactionTypeService.save(transactionType)

    then:

    transactionType.id
  }

  void "update transactionType"() {
    given:

    transactionTypeTestDataService.loadData()
    def transactionType = TransactionType.first()
    def id = transactionType.id

    when:

    transactionType.name = 'TEST'
    transactionTypeService.update(transactionType)

    then:

    def temp = TransactionType.get(id)
    temp.name == 'TEST'
  }

  void "delete transactionType"() {
    given:

    transactionTypeTestDataService.loadData()
    def transactionType = TransactionType.first()
    def id = transactionType.id

    when:

    transactionTypeService.delete(transactionType)

    then:

    TransactionType.get(id) == null
  }


  void "test name for Null"() {
    given:

    transactionTypeTestDataService.loadData()
    TransactionType transactionType = TransactionType.first()
    transactionType.name = null

    when:

    transactionTypeService.update(transactionType);

    then:

    transactionType.errors.getFieldError("name").code == "nullable"

  }

  void "test name for unique"() {
    given:


    def transactionTypeList = (List<LoaderDTO>) TransactionTypeTestDataLoader.load(2)
    def transactionType = (TransactionType) transactionTypeList.first().object

    def temp = transactionType.name;

    when:

    transactionTypeService.save(transactionType);

    def testTransactionType = (TransactionType) transactionTypeList[1].object
    testTransactionType.name = temp;

    transactionTypeService.save(testTransactionType);

    then:

    testTransactionType.errors.getFieldError("name").code == "unique"
  }
}
    