
package com.genrocket.bank

import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/18/2016.
 */
class TransactionServiceConstraintSpec extends IntegrationSpec {
  def transactionTestDataService
  def transactionService

  void "test account for Null"() {
    given:

    transactionTestDataService.loadData()
    Transaction transaction = Transaction.first()
    transaction.account = null

    when:

    transactionService.update(transaction);

    then:

    transaction.errors.getFieldError("account").code == "nullable"

  }

  void "test amount for Null"() {
    given:

    transactionTestDataService.loadData()
    Transaction transaction = Transaction.first()
    transaction.amount = null

    when:

    transactionService.update(transaction);

    then:

    transaction.errors.getFieldError("amount").code == "nullable"

  }

  void "test transactionType for Null"() {
    given:

    transactionTestDataService.loadData()
    Transaction transaction = Transaction.first()
    transaction.transactionType = null

    when:

    transactionService.update(transaction);

    then:

    transaction.errors.getFieldError("transactionType").code == "nullable"

  }

  void "test user for Null"() {
    given:

    transactionTestDataService.loadData()
    Transaction transaction = Transaction.first()
    transaction.user = null

    when:

    transactionService.update(transaction);

    then:

    transaction.errors.getFieldError("user").code == "nullable"

  }
}
    