package com.genrocket.bank

import com.genRocket.tdl.LoaderDTO
import com.genrocket.bank.testDataLoader.UserTestDataLoader
import grails.test.spock.IntegrationSpec

/**
 * Generated By GenRocket 10/16/2016.
 */
class UserServiceIntegrationSpec extends IntegrationSpec {
  def userTestDataService
  def userService

  void "create user"() {
    given:


    when:

    def userList = (List<LoaderDTO>) UserTestDataLoader.load()
    def user = (User) userList.first().object

    userService.save(user)

    then:

    user.id
  }

  void "update user"() {
    given:

    userTestDataService.loadData()
    def user = User.first()
    def id = user.id

    when:

    user.firstName = 'TEST'
    userService.update(user)

    then:

    def temp = User.get(id)
    temp.firstName == 'TEST'
  }

  void "delete user"() {
    given:

    userTestDataService.loadData()
    def user = User.first()
    def id = user.id

    when:

    userService.delete(user)

    then:

    User.get(id) == null
  }

}
    