package com.genrocket.bank

import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class AccountTypeService {

  def save(AccountType accountType) {
    accountType.save()
  }

  def update(AccountType accountType) {
    accountType.save()
  }

  def delete(AccountType accountType) {
    accountType.delete()
  }
}
    