package com.genrocket.bank

import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class BranchService {

  def save(Branch branch) {
    branch.save()
  }

  def update(Branch branch) {
    branch.save()
  }

  def delete(Branch branch) {
    branch.delete()
  }
}
    