package com.genrocket.bank

import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class CustomerService {

  def save(Customer customer) {
    customer.save()
  }

  def enableCustomer(Customer customer) {
    customer.enabled = true
    customer.save()
  }

  def disableCustomer(Customer customer) {
    customer.enabled = false
    customer.save()
  }
}
    