package com.genrocket.bank

import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class CustomerLevelService {

  def save(CustomerLevel customerLevel) {
    customerLevel.save()
  }

  def update(CustomerLevel customerLevel) {
    customerLevel.save()
  }

  def delete(CustomerLevel customerLevel) {
    customerLevel.delete()
  }
}
    