package com.genrocket.bank

import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class CustomerService {

  def save(Customer customer) {
    customer.save()
  }

  def update(Customer customer) {
    customer.save()
  }

  def delete(Customer customer) {
    customer.delete()
  }
}
    