package com.genrocket.bank

import org.springframework.transaction.annotation.Transactional

/**
 * Generated By GenRocket 10/16/2016.
 */
@Transactional
class TransactionService {

  def save(Transaction transaction) {
    transaction.save(failOnError: true)
  }

  def update(Transaction transaction) {
    transaction.save(failOnError: true)
  }

  def delete(Transaction transaction) {
    transaction.delete()
  }
}
    