
      package com.genrocket.bank

      import org.springframework.transaction.annotation.Transactional

      /**
       * Generated By GenRocket 10/16/2016.
       */
      @Transactional
      class UserService {

        def save(User user) {
          user.save()
        }

        def update(User user) {
          user.save()
        }

        def delete(User user) {
          user.delete()
        }
      }
    