package com.genrocket.bank.testDataLoader

import com.genrocket.bank.Account
import com.genRocket.tdl.LoaderDTO
import com.genRocket.tdl.TestDataLoader
import com.genRocket.tdl.ScenarioParams


/**
 * Generated By GenRocket 10/16/2016.
 */
class AccountTestDataLoader {
  static SCENARIO_PATH = 'GENROCKET_BANK_SCENARIOS'
  static SCENARIO = 'AccountScenario'
  static SCENARIO_DOMAIN = 'Account'

  static load(Integer loopCount = 1) {
    ScenarioParams scenarioParams = new ScenarioParams(SCENARIO_PATH, SCENARIO, SCENARIO_DOMAIN, loopCount)
    def data = TestDataLoader.runScenario(scenarioParams)
    List<LoaderDTO> testData = []

    data.each { node ->
      LoaderDTO dto = new LoaderDTO()

      dto.map.put('accountType', node.accountType)
      dto.map.put('branch', node.branch)

      node.remove('accountType')
      node.remove('branch')

      dto.object = new Account(node)
      testData.add(dto)
    }

    return testData
  }
}
    