package com.genrocket.bank.testDataLoader

import com.genrocket.bank.Card
import com.genRocket.tdl.LoaderDTO
import com.genRocket.tdl.TestDataLoader
import com.genRocket.tdl.ScenarioParams
import java.text.SimpleDateFormat

/**
 * Generated By GenRocket 10/16/2016.
 */
class CardTestDataLoader {
  static SCENARIO_PATH = 'GENROCKET_BANK_SCENARIOS'
  static SCENARIO = 'CardScenario'
  static SCENARIO_DOMAIN = 'Card'

  static load(Integer loopCount = 1) {
    ScenarioParams scenarioParams = new ScenarioParams(SCENARIO_PATH, SCENARIO, SCENARIO_DOMAIN, loopCount)
    def data = TestDataLoader.runScenario(scenarioParams)
    List<LoaderDTO> testData = []

    data.each { node ->
      LoaderDTO dto = new LoaderDTO()

      dto.map.put('cardType', node.cardType)
      dto.map.put('customer', node.customer)

      node.remove('cardType')
      node.remove('customer')

      node.dateActivated = new SimpleDateFormat('yyyy-MM-dd').parse(node.dateActivated)
      node.dateDeactivated = new SimpleDateFormat('yyyy-MM-dd').parse(node.dateDeactivated)
      node.dateExpired = new SimpleDateFormat('yyyy-MM-dd').parse(node.dateExpired)
      node.dateIssued = new SimpleDateFormat('yyyy-MM-dd').parse(node.dateIssued)


      dto.object = new Card(node)
      testData.add(dto)
    }

    return testData
  }
}
    